name: CI

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
      SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{ hashFiles('**/packgage-lock.json') }}
          restore-keys: ${{runner.os}}-node-
      - run: npm ci
      - run: npm run format:check
      - run: npm run test -- --coverage --watchAll=false
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: CI=false npm run build
      - name: Upload Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: npx surge --project ./build --domain alcoholic-business.surge.sh
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx surge --project ./build --domain alcoholic-business-prod.surge.sh
      - name: Upload Coverage Report
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx code-cov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
